name: Requiring module in SSR

on:
  - pull_request

jobs:
  ssr:
    name: Cypress
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 14

      - run: yarn install && yarn build-module

      - name: Require module via node
        run: cd dist; node -e "require('./module')"
